accessmanagement:
  enabled: ${ACCESS_MANAGEMENT_EXPORT_ENABLED:true}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${AM_DB_HOST:localhost}:${AM_DB_PORT:5433}/${AM_DB_NAME:am}${AM_DB_PARAMS:}
    username: ${AM_DB_USERNAME:amuser}
    password: ${AM_DB_PASSWORD:ampass}
    properties:
      charSet: UTF-8
